"""add country state city to restaurants

Revision ID: cfb0846824e5
Revises: 55729f4e5fc3
Create Date: 2026-01-07 06:21:14.614235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb0846824e5'
down_revision: Union[str, Sequence[str], None] = '55729f4e5fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('country_code', sa.String(length=5), nullable=True))
    op.add_column('restaurants', sa.Column('state_code', sa.String(length=10), nullable=True))
    op.add_column('restaurants', sa.Column('city_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'city_code')
    op.drop_column('restaurants', 'state_code')
    op.drop_column('restaurants', 'country_code')
    # ### end Alembic commands ###
