"""Add landmark and restaurant_specific_categories

Revision ID: 88596672156b
Revises: 323131e4b423
Create Date: 2026-01-30 16:36:25.504141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88596672156b'
down_revision: Union[str, Sequence[str], None] = '323131e4b423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_unique_constraint('uq_category_name_restaurant', 'categories', ['name', 'restaurant_id'])
    op.create_foreign_key(None, 'categories', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('restaurants', sa.Column('landmark', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'landmark')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint('uq_category_name_restaurant', 'categories', type_='unique')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'restaurant_id')
    # ### end Alembic commands ###
