"""add logo_url to restaurants

Revision ID: ecaedef2d784
Revises: cfb0846824e5
Create Date: 2026-01-10 00:22:35.060689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecaedef2d784'
down_revision: Union[str, Sequence[str], None] = 'cfb0846824e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_images', 'image_url',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.add_column('restaurants', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'logo_url')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.alter_column('product_images', 'image_url',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###
